### PR TITLE
Convert datamodule classes into attrs classes.

### PR DESCRIPTION
**Pull request by MylesBartlett**

### CODE REVIEW

**Comment by MylesBartlett** [comment]
We need a variant of parsable that operates at the class level

**Comment by thomkeh** [comment]
Does configen work on this?

**Comment by MylesBartlett** [comment]
> Does configen work on this?

Yes; do you think I would have spent an hour making the switch without first testing for configen compatibility? configen doesn't work with the standard attr.s decorator but it does work with the attr.define decorator designed for pyright compatibility.

**Comment by olliethomas** [comment]
> > Does configen work on this?
> 
> Yes; do you think I would have spent an hour making the switch without first testing for configen compatibility? configen doesn't work with the standard attr.s decorator but it does work with the attr.define decorator designed for pyright compatibility.

This pleasantly surprises me.

**Review by thomkeh — APPROVED** [review]
LGTM

**Pull request merged**
